# Generated by Django 2.0.3 on 2018-03-28 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='roles',
            field=models.ManyToManyField(blank=True, to='CRM_test.Role'),
        ),
    ]
