# Generated by Django 2.0.3 on 2018-03-30 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM_test', '0003_auto_20180328_1718'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': '菜单', 'verbose_name_plural': '菜单'},
        ),
    ]
